const authTypes = {
  // Send phone verification code
  "SEND_PHONE_VERIFICATION_CODE_REQUEST": "SEND_PHONE_VERIFICATION_CODE_REQUEST",
  "SEND_PHONE_VERIFICATION_CODE_SUCCESS": "SEND_PHONE_VERIFICATION_CODE_SUCCESS",
  "SEND_PHONE_VERIFICATION_CODE_FAILURE": "SEND_PHONE_VERIFICATION_CODE_FAILURE",
};

export default authTypes;
