const authTypes = {
  // Send phone verification code
  "SEND_PHONE_VERIFICATION_CODE_REQUEST": "SEND_PHONE_VERIFICATION_CODE_REQUEST",
  "SEND_PHONE_VERIFICATION_CODE_SUCCESS": "SEND_PHONE_VERIFICATION_CODE_SUCCESS",
  "SEND_PHONE_VERIFICATION_CODE_FAILURE": "SEND_PHONE_VERIFICATION_CODE_FAILURE",

  // Send email
  "SEND_EMAIL_REQUEST": "SEND_EMAIL_REQUEST",
  "SEND_EMAIL_SUCCESS": "SEND_EMAIL_SUCCESS",
  "SEND_EMAIL_FAILURE": "SEND_EMAIL_FAILURE",
};

export default authTypes;
