const blogTypes = {
  // Clear blog reducer
  "CLEAR_POSTS_LIST": "CLEAR_POSTS_LIST",

  // Get blog list
  "GET_POSTS_REQUEST": "GET_POSTS_REQUEST",
  "GET_POSTS_SUCCESS": "GET_POSTS_SUCCESS",
  "GET_POSTS_FAILURE": "GET_POSTS_FAILURE",

  // Get single post
  "GET_SINGLE_POST_REQUEST": "GET_SINGLE_POST_REQUEST",
  "GET_SINGLE_POST_SUCCESS": "GET_SINGLE_POST_SUCCESS",
  "GET_SINGLE_POST_FAILURE": "GET_SINGLE_POST_FAILURE",

  // Add new blog
  "ADD_NEW_POST_REQUEST": "ADD_NEW_POST_REQUEST",
  "ADD_NEW_POST_SUCCESS": "ADD_NEW_POST_SUCCESS",
  "ADD_NEW_POST_FAILURE": "ADD_NEW_POST_FAILURE",

  // Update blog
  "UPDATE_POST_REQUEST": "UPDATE_POST_REQUEST",
  "UPDATE_POST_SUCCESS": "UPDATE_POST_SUCCESS",
  "UPDATE_POST_FAILURE": "UPDATE_POST_FAILURE",

  // Delete blog
  "DELETE_POST_REQUEST": "DELETE_POST_REQUEST",
  "DELETE_POST_SUCCESS": "DELETE_POST_SUCCESS",
  "DELETE_POST_FAILURE": "DELETE_POST_FAILURE",

  // Vote blog
  "VOTE_POST_REQUEST": "VOTE_POST_REQUEST",
  "VOTE_POST_SUCCESS": "VOTE_POST_SUCCESS",
  "VOTE_POST_FAILURE": "VOTE_POST_FAILURE",

  // Report blog
  "REPORT_POST_REQUEST": "REPORT_POST_REQUEST",
  "REPORT_POST_SUCCESS": "REPORT_POST_SUCCESS",
  "REPORT_POST_FAILURE": "REPORT_POST_FAILURE",
};

export default blogTypes;
