const businessTypes = {
  // Get business list
  "GET_BUSINESS_LIST_REQUEST": "GET_BUSINESS_LIST_REQUEST",
  "GET_BUSINESS_LIST_SUCCESS": "GET_BUSINESS_LIST_SUCCESS",
  "GET_BUSINESS_LIST_FAILURE": "GET_BUSINESS_LIST_FAILURE",

  // Add business
  "ADD_BUSINESS_REQUEST": "ADD_BUSINESS_REQUEST",
  "ADD_BUSINESS_SUCCESS": "ADD_BUSINESS_SUCCESS",
  "ADD_BUSINESS_FAILURE": "ADD_BUSINESS_FAILURE",
};

export default businessTypes;
