const businessTypes = {
  // Get business list
  "GET_BUSINESS_LIST_REQUEST": "GET_BUSINESS_LIST_REQUEST",
  "GET_BUSINESS_LIST_SUCCESS": "GET_BUSINESS_LIST_SUCCESS",
  "GET_BUSINESS_LIST_FAILURE": "GET_BUSINESS_LIST_FAILURE",

  // Get single business
  "GET_SINGLE_BUSINESS_REQUEST": "GET_SINGLE_BUSINESS_REQUEST",
  "GET_SINGLE_BUSINESS_SUCCESS": "GET_SINGLE_BUSINESS_SUCCESS",
  "GET_SINGLE_BUSINESS_FAILURE": "GET_SINGLE_BUSINESS_FAILURE",

  // Add business
  "ADD_BUSINESS_REQUEST": "ADD_BUSINESS_REQUEST",
  "ADD_BUSINESS_SUCCESS": "ADD_BUSINESS_SUCCESS",
  "ADD_BUSINESS_FAILURE": "ADD_BUSINESS_FAILURE",

  // Update business
  "UPDATE_BUSINESS_REQUEST": "UPDATE_BUSINESS_REQUEST",
  "UPDATE_BUSINESS_SUCCESS": "UPDATE_BUSINESS_SUCCESS",
  "UPDATE_BUSINESS_FAILURE": "UPDATE_BUSINESS_FAILURE",

  // Delete business
  "DELETE_BUSINESS_REQUEST": "DELETE_BUSINESS_REQUEST",
  "DELETE_BUSINESS_SUCCESS": "DELETE_BUSINESS_SUCCESS",
  "DELETE_BUSINESS_FAILURE": "DELETE_BUSINESS_FAILURE",
};

export default businessTypes;
