const businessTypes = {

  // Clear business reduer
  "CLEAR_BUSINESS_LIST": "CLEAR_BUSINESS_LIST",

  // Get business list
  "GET_BUSINESS_LIST_REQUEST": "GET_BUSINESS_LIST_REQUEST",
  "GET_BUSINESS_LIST_SUCCESS": "GET_BUSINESS_LIST_SUCCESS",
  "GET_BUSINESS_LIST_FAILURE": "GET_BUSINESS_LIST_FAILURE",

  // Get single business
  "GET_SINGLE_BUSINESS_REQUEST": "GET_SINGLE_BUSINESS_REQUEST",
  "GET_SINGLE_BUSINESS_SUCCESS": "GET_SINGLE_BUSINESS_SUCCESS",
  "GET_SINGLE_BUSINESS_FAILURE": "GET_SINGLE_BUSINESS_FAILURE",

  // Report business
  "REPORT_BUSINESS_REQUEST": "REPORT_BUSINESS_REQUEST",
  "REPORT_BUSINESS_SUCCESS": "REPORT_BUSINESS_SUCCESS",
  "REPORT_BUSINESS_FAILURE": "REPORT_BUSINESS_FAILURE",
};

export default businessTypes;
