const commentTypes = {
    // Clear comment reducer
    "CLEAR_COMMENTS_LIST": "CLEAR_COMMENTS_LIST",

    // Get comments
    "GET_COMMENTS_REQUEST": "GET_COMMENTS_REQUEST",
    "GET_COMMENTS_SUCCESS": "GET_COMMENTS_SUCCESS",
    "GET_COMMENTS_FAILURE": "GET_COMMENTS_FAILURE",

    // Add new comment
    "ADD_NEW_COMMENT_REQUEST": "ADD_NEW_COMMENT_REQUEST",
    "ADD_NEW_COMMENT_SUCCESS": "ADD_NEW_COMMENT_SUCCESS",
    "ADD_NEW_COMMENT_FAILURE": "ADD_NEW_COMMENT_FAILURE",

    // Update comment
    "UPDATE_COMMENT_REQUEST": "UPDATE_COMMENT_REQUEST",
    "UPDATE_COMMENT_SUCCESS": "UPDATE_COMMENT_SUCCESS",
    "UPDATE_COMMENT_FAILURE": "UPDATE_COMMENT_FAILURE",

    // Delete comment
    "DELETE_COMMENT_REQUEST": "DELETE_COMMENT_REQUEST",
    "DELETE_COMMENT_SUCCESS": "DELETE_COMMENT_SUCCESS",
    "DELETE_COMMENT_FAILURE": "DELETE_COMMENT_FAILURE",

    // Vote comment
    "VOTE_COMMENT_REQUEST": "VOTE_COMMENT_REQUEST",
    "VOTE_COMMENT_SUCCESS": "VOTE_COMMENT_SUCCESS",
    "VOTE_COMMENT_FAILURE": "VOTE_COMMENT_FAILURE",

}

export default commentTypes;
