const notificationTypes = {
  // Clear notification
  "CLEAR_NOTIFICATION_LIST": "CLEAR_NOTIFICATION_LIST",

  // Get notifications
  "GET_NOTIFICATION_REQUEST": "GET_NOTIFICATION_REQUEST",
  "GET_NOTIFICATION_SUCCESS": "GET_NOTIFICATION_SUCCESS",
  "GET_NOTIFICATION_FAILURE": "GET_NOTIFICATION_FAILURE",

  // Get new notifications
  "GET_UNREAD_COUNT_REQUEST": "GET_UNREAD_COUNT_REQUEST",
  "GET_UNREAD_COUNT_SUCCESS": "GET_UNREAD_COUNT_SUCCESS",
  "GET_UNREAD_COUNT_FAILURE": "GET_UNREAD_COUNT_FAILURE",

  // Delete notification
  "DELETE_NOTIFICATION_REQUEST": "DELETE_NOTIFICATION_REQUEST",
  "DELETE_NOTIFICATION_SUCCESS": "DELETE_NOTIFICATION_SUCCESS",
  "DELETE_NOTIFICATION_FAILURE": "DELETE_NOTIFICATION_FAILURE",

  // Clear read notifications
  "CLEAR_READ_NOTIFICATION_REQUEST": "CLEAR_READ_NOTIFICATION_REQUEST",
  "CLEAR_READ_NOTIFICATION_SUCCESS": "CLEAR_READ_NOTIFICATION_SUCCESS",
  "CLEAR_READ_NOTIFICATION_FAILURE": "CLEAR_READ_NOTIFICATION_FAILURE",
};

export default notificationTypes;
