const pcaTypes = {
  // Get cities
  "GET_CITIES_REQUEST": "GET_CITIES_REQUEST",
  "GET_CITIES_SUCCESS": "GET_CITIES_SUCCESS",
  "GET_CITIES_FAILURE": "GET_CITIES_FAILURE",

  // Get areas
  "GET_AREAS_REQUEST": "GET_AREAS_REQUEST",
  "GET_AREAS_SUCCESS": "GET_AREAS_SUCCESS",
  "GET_AREAS_FAILURE": "GET_AREAS_FAILURE",
};

export default pcaTypes;
