const pcaTypes = {
  // Get provinces
  "GET_PROVINCES_REQUEST": "GET_PROVINCES_REQUEST",
  "GET_PROVINCES_SUCCESS": "GET_PROVINCES_SUCCESS",
  "GET_PROVINCES_FAILURE": "GET_PROVINCES_FAILURE",
  
  // Get cities
  "GET_CITIES_REQUEST": "GET_CITIES_REQUEST",
  "GET_CITIES_SUCCESS": "GET_CITIES_SUCCESS",
  "GET_CITIES_FAILURE": "GET_CITIES_FAILURE",

  // Get areas
  "GET_AREAS_REQUEST": "GET_AREAS_REQUEST",
  "GET_AREAS_SUCCESS": "GET_AREAS_SUCCESS",
  "GET_AREAS_FAILURE": "GET_AREAS_FAILURE",

  // Get general areas
  "GET_GENERAL_AREAS_REQUEST": "GET_GENERAL_AREAS_REQUEST",
  "GET_GENERAL_AREAS_SUCCESS": "GET_GENERAL_AREAS_SUCCESS",
  "GET_GENERAL_AREAS_FAILURE": "GET_GENERAL_AREAS_FAILURE",
};

export default pcaTypes;
