const reviewTypes = {
    // Get reviews
    "GET_REVIEWS_REQUEST": "GET_REVIEWS_REQUEST",
    "GET_REVIEWS_SUCCESS": "GET_REVIEWS_SUCCESS",
    "GET_REVIEWS_FAILURE": "GET_REVIEWS_FAILURE",

    // Add new review
    "ADD_NEW_REVIEW_REQUEST": "ADD_NEW_REVIEW_REQUEST",
    "ADD_NEW_REVIEW_SUCCESS": "ADD_NEW_REVIEW_SUCCESS",
    "ADD_NEW_REVIEW_FAILURE": "ADD_NEW_REVIEW_FAILURE",
}

export default reviewTypes;
