const reviewTypes = {
    // Clear review reducer
    "CLEAR_REVIEWS_LIST": "CLEAR_REVIEWS_LIST",

    // Get reviews
    "GET_REVIEWS_REQUEST": "GET_REVIEWS_REQUEST",
    "GET_REVIEWS_SUCCESS": "GET_REVIEWS_SUCCESS",
    "GET_REVIEWS_FAILURE": "GET_REVIEWS_FAILURE",

    // Add new review
    "ADD_NEW_REVIEW_REQUEST": "ADD_NEW_REVIEW_REQUEST",
    "ADD_NEW_REVIEW_SUCCESS": "ADD_NEW_REVIEW_SUCCESS",
    "ADD_NEW_REVIEW_FAILURE": "ADD_NEW_REVIEW_FAILURE",

    // Update review
    "UPDATE_REVIEW_REQUEST": "UPDATE_REVIEW_REQUEST",
    "UPDATE_REVIEW_SUCCESS": "UPDATE_REVIEW_SUCCESS",
    "UPDATE_REVIEW_FAILURE": "UPDATE_REVIEW_FAILURE",

    // Delete review
    "DELETE_REVIEW_REQUEST": "DELETE_REVIEW_REQUEST",
    "DELETE_REVIEW_SUCCESS": "DELETE_REVIEW_SUCCESS",
    "DELETE_REVIEW_FAILURE": "DELETE_REVIEW_FAILURE",
}

export default reviewTypes;
