const userTypes = {
  "UPDATE_USERNAME": "UPDATE_USERNAME",

  // Login
  "LOGIN_REQUEST": 'LOGIN_REQUEST',
  "LOGIN_SUCCESS": 'LOGIN_SUCCESS',
  "LOGIN_FAILURE": 'LOGIN_FAILURE',

  // Register
  "REGISTER_REQUEST": 'REGISTER_REQUEST',
  "REGISTER_SUCCESS": 'REGISTER_SUCCESS',
  "REGISTER_FAILURE": 'REGISTER_FAILURE',

  // Account Verify
  "VERIFY_REQUEST": "VERIFY_REQUEST",
  "VERIFY_SUCCESS": "VERIFY_SUCCESS",
  "VERIFY_FAILURE": "VERIFY_FAILURE",

  // Change Password
  "CHANGE_PASSWORD_REQUEST": "CHANGE_PASSWORD_REQUEST",
  "CHANGE_PASSWORD_SUCCESS": "CHANGE_PASSWORD_SUCCESS",
  "CHANGE_PASSWORD_FAILURE": "CHANGE_PASSWORD_FAILURE",

  // Get User By Id
  "GET_USER_BY_ID_REQUEST": "GET_USER_BY_ID_REQUEST",
  "GET_USER_BY_ID_SUCCESS": "GET_USER_BY_ID_SUCCESS",
  "GET_USER_BY_ID_FAILURE": "GET_USER_BY_ID_FAILURE",

  // Log out
  "LOGOUT_REQUEST": "LOGOUT_REQUEST",
  "LOGOUT_SUCCESS": "LOGOUT_SUCCESS",
  "LOGOUT_FAILURE": "LOGOUT_FAILURE",

  // Update user info
  "UPDATE_USER_PROFILE_REQUEST": "UPDATE_USER_PROFILE_REQUEST",
  "UPDATE_USER_PROFILE_SUCCESS": "UPDATE_USER_PROFILE_SUCCESS",
  "UPDATE_USER_PROFILE_FAILURE": "UPDATE_USER_PROFILE_FAILURE",

};

export default userTypes;
