const userTypes = {
  "CLEAR_USER_REDUCER":"CLEAR_USER_REDUCER",
  "UPDATE_USERNAME": "UPDATE_USERNAME",

  // Login
  "LOGIN_REQUEST": 'LOGIN_REQUEST',
  "LOGIN_SUCCESS": 'LOGIN_SUCCESS',
  "LOGIN_FAILURE": 'LOGIN_FAILURE',

  // Register
  "REGISTER_REQUEST": 'REGISTER_REQUEST',
  "REGISTER_SUCCESS": 'REGISTER_SUCCESS',
  "REGISTER_FAILURE": 'REGISTER_FAILURE',

  // Account Verify
  "VERIFY_REQUEST": "VERIFY_REQUEST",
  "VERIFY_SUCCESS": "VERIFY_SUCCESS",
  "VERIFY_FAILURE": "VERIFY_FAILURE",

  // Change Password
  "CHANGE_PASSWORD_REQUEST": "CHANGE_PASSWORD_REQUEST",
  "CHANGE_PASSWORD_SUCCESS": "CHANGE_PASSWORD_SUCCESS",
  "CHANGE_PASSWORD_FAILURE": "CHANGE_PASSWORD_FAILURE",

  // Get User By Id
  "GET_MYSELF_REQUEST": "GET_MYSELF_REQUEST",
  "GET_MYSELF_SUCCESS": "GET_MYSELF_SUCCESS",
  "GET_MYSELF_FAILURE": "GET_MYSELF_FAILURE",

  // Log out
  "LOGOUT_REQUEST": "LOGOUT_REQUEST",
  "LOGOUT_SUCCESS": "LOGOUT_SUCCESS",
  "LOGOUT_FAILURE": "LOGOUT_FAILURE",

  // Update user info
  "UPDATE_USER_PROFILE_REQUEST": "UPDATE_USER_PROFILE_REQUEST",
  "UPDATE_USER_PROFILE_SUCCESS": "UPDATE_USER_PROFILE_SUCCESS",
  "UPDATE_USER_PROFILE_FAILURE": "UPDATE_USER_PROFILE_FAILURE",

  // Upload user profile profilePhoto
  "UPLOAD_PROFILE_PHOTO_REQUEST": "UPLOAD_PROFILE_PHOTO_REQUEST",
  "UPLOAD_PROFILE_PHOTO_SUCCESS": "UPLOAD_PROFILE_PHOTO_SUCCESS",
  "UPLOAD_PROFILE_PHOTO_FAILURE": "UPLOAD_PROFILE_PHOTO_FAILURE",

  // Update user's mobile phone number
  "UPDATE_MOBILE_PHONE_REQUEST": "UPDATE_MOBILE_PHONE_REQUEST",
  "UPDATE_MOBILE_PHONE_SUCCESS": "UPDATE_MOBILE_PHONE_SUCCESS",
  "UPDATE_MOBILE_PHONE_FAILURE": "UPDATE_MOBILE_PHONE_FAILURE",

  // Add or delete user's favorite business
  "FAVOR_OPERATION_REQUEST": "FAVOR_OPERATION_REQUEST",
  "FAVOR_OPERATION_SUCCESS": "FAVOR_OPERATION_SUCCESS",
  "FAVOR_OPERATION_FAILURE": "FAVOR_OPERATION_FAILURE",

};

export default userTypes;
